# <center>Тема 2. Углубленные приемы pandas, collections, numpy</center>
## <center>Практическое задание. Работа с векторами в библиотеке NumPy</center>

In [2]:
import numpy as np
import pandas as pd

**1. Создайте numpy массив с числами от 100 с шагом в 10, размера 10х5**

In [19]:
a = np.arange(100, 100 + 10 * 10 * 5, 10)
a.shape = (10,5)
a

array([[100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240],
       [250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490],
       [500, 510, 520, 530, 540],
       [550, 560, 570, 580, 590]])

**2. Создайте numpy массив с числами от 100 с шагом в 10, размера 10х5 заполеннный змейкой**  
---------->  
<---------  
---------->  

In [33]:
a = [line if indx%2 == 0 else line[::-1] for indx, line in enumerate(a)]
a

[array([100, 110, 120, 130, 140]),
 array([150, 160, 170, 180, 190]),
 array([200, 210, 220, 230, 240]),
 array([250, 260, 270, 280, 290]),
 array([300, 310, 320, 330, 340]),
 array([350, 360, 370, 380, 390]),
 array([400, 410, 420, 430, 440]),
 array([450, 460, 470, 480, 490]),
 array([500, 510, 520, 530, 540]),
 array([550, 560, 570, 580, 590])]

**3. Вычтите из каждого ряда первого массива соответствующее значение из второго**  
Result
array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [35]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [39]:
b_1d.shape = (3,1)
a_2d - b_1d

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

**4. Заменить все положительные числа массива на 1, отрицательные на 0**

In [3]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=(3000,3000))

array([[-316, -441,  653, ...,  773,  961, -475],
       [-187,  456, -432, ...,  168,  273, -169],
       [ 936,  475, -128, ...,  408, -892, -310],
       ...,
       [-921,  396,  457, ...,  646, -450, -387],
       [ 645,  943, -435, ...,  863, -920,  790],
       [ 641, -548,  379, ...,  347,  -67, -352]])

In [6]:
X = np.where(X > 0, 1, 0)
X

array([[0, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 1, 0],
       [1, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 1, ..., 1, 0, 0],
       [1, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 1, 0, 0]])

**5. Создать numpy массив нулей размера NхM c границей из единиц, шириной K**

In [9]:
N = 10
M = 6
K = 2

In [74]:
a = np.zeros((N, M))
a1 = np.ones((N, K))

a = np.concatenate((a, a1), axis=1)
a = np.concatenate((a1, a), axis=1)

a = a.T

a = np.concatenate((a, a1), axis=1)
a = np.concatenate((a1, a), axis=1)
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**6. Вывести все name и среднее число заказов типа 2 по месяцам, для которых общая сумма заказов за месяц, в которых число заказов типа 1 больше числа заказов типа 2, превышает среднюю сумму заказов по всем месяцам.**  
Дополнительно: не использовать присваивание

In [75]:
# не менять
np.random.seed(17)
data = pd.DataFrame({'name': np.random.randint(0, 10, size=1000),
                     'date': pd.date_range('2019-01-01', '2020-01-01', periods=1000),
                     'order_type_1': np.random.randint(0, 100, size=1000),
                     'order_type_2': np.random.randint(0, 100, size=1000)})
data.loc[data['order_type_1'] % 5 == 0, 'order_type_1'] = np.nan
data.loc[data['order_type_2'] % 3 == 0, 'order_type_2'] = np.nan
data.head()

# order_type - сумма заказа типа 1 и типа 2 на определенную дату. NaN если заказа не было

name                          date  order_type_1  order_type_2
0     1 2019-01-01 00:00:00.000000000           9.0          61.0
1     6 2019-01-01 08:46:07.567567567          47.0           NaN
2     6 2019-01-01 17:32:15.135135135          54.0           NaN
3     9 2019-01-02 02:18:22.702702702          83.0           NaN
4     0 2019-01-02 11:04:30.270270270          18.0           NaN

In [245]:

agg = data.groupby(by=[pd.Grouper(key='date', freq='M'), 'name']).agg(
    {
        'order_type_1': ['mean', 'sum', 'count'],
        'order_type_2': ['mean', 'sum', 'count']
    }
)
agg = agg[agg['order_type_1']['count'] > agg['order_type_2']['count']]
agg

order_type_1              order_type_2             
                        mean    sum count         mean    sum count
date       name                                                    
2019-01-31 0       38.000000  152.0     4    29.000000   29.0     1
           3       50.625000  405.0     8    66.333333  199.0     3
           5       63.666667  191.0     3    16.500000   33.0     2
           6       49.100000  491.0    10    34.000000  204.0     6
           7       48.000000  240.0     5    65.000000  195.0     3
...                      ...    ...   ...          ...    ...   ...
2019-12-31 4       52.272727  575.0    11    66.166667  397.0     6
           5       44.500000  267.0     6    50.600000  253.0     5
           6       52.727273  580.0    11    47.142857  330.0     7
           8       33.571429  235.0     7    40.000000  160.0     4
2020-01-31 9       91.000000   91.0     1          NaN    0.0     0

[85 rows x 6 columns]

In [240]:
aver = agg['order_type_1']['sum'] + agg['order_type_2']['sum']
aver = aver.mean()
aver

573.4588235294118

In [246]:
agg[agg['order_type_1']['sum'] + agg['order_type_2']['sum'] > aver]['order_type_2']['mean']

date        name
2019-01-31  3       66.333333
            6       34.000000
            8       55.285714
            9       37.800000
2019-02-28  2       64.666667
            5       50.600000
            8       66.400000
2019-03-31  0       39.500000
            3       58.833333
            4       62.333333
            6       41.500000
            8       47.000000
2019-04-30  2       35.000000
            5       61.166667
            6       50.375000
            7       42.857143
2019-05-31  0       35.714286
            2       24.800000
            5       51.800000
2019-06-30  1       39.571429
            3       63.000000
2019-07-31  0       38.100000
            4       43.875000
            5       58.750000
2019-08-31  2       33.200000
            3       59.000000
            4       48.666667
2019-09-30  0       56.600000
            1       69.500000
            2       66.750000
            7       37.833333
2019-10-31  2       51.000000
            6       26.